# Generated by Django 5.0.2 on 2024-03-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zaznam',
            new_name='Kniha',
        ),
    ]
