# Generated by Django 5.0.2 on 2024-03-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_kniha_rok_vydani_alter_kniha_datum_vytvoreni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='obrazek',
            field=models.TextField(default='oaskdpkda'),
            preserve_default=False,
        ),
    ]
